name: 1.22 on debian

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build-and-push-docker-image:
        name: "Build 1.22 on push to docker hub"
        uses: giuseppemorelli/docker-devbox-golang/.github/workflows/build_and_push.yml@main
        with:
            tagversion: '1.22'
            folder: './golang-1.22-debian'
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
